### ISSUE TITLE
Rename file

### ISSUE THREAD

**Issue by lubushyn** [Wildhoney/ngDroplet#19]
Hi. Does it possible rename file before upload?

**Comment by Wildhoney** [comment]
Sadly not, but you could [setup a `requestPostData` object](https://github.com/Wildhoney/ngDroplet/blob/master/components/ngDroplet.js#L639) to map the `File` objects to their final filename, and then consult that map on the back-end to rename them individually.

**Comment by lubushyn** [comment]
I see. Thanks man.
