### ISSUE TITLE
Image Preview not showing

### ISSUE THREAD

**Issue by himelnagrana** [Wildhoney/ngDroplet#21]
We have followed all the mentioned steps and the example. 
After dragging and dropping - the files are added into the ````<ul class="files">```` section. 
The preview image is there as background and ````src```` in ````base54```` encoded value. But the browser cannot show the image preview. In chrome it gives a warning saying:

````Resource interpreted as Image but transferred with MIME type text/html: ````

I have tested with the src ````base64```` codes into separate html file both as ````src```` and ````background:url()````. They works fine.

Can you please shed some light on this - which we are missing?
Thanks in advance.

**Comment by Wildhoney** [comment]
Everything works [in the example](http://ng-droplet.herokuapp.com/) using exactly the same image?

**Comment by himelnagrana** [comment]
Yes :-( it works there. 
I have made a copy of the example code in my local and it works there too.

**Comment by Wildhoney** [comment]
Hmm, it's difficult to diagnose without being able to replicate the issue.

Is there any chance you can share your code, or let me see where you're using it? I'll be able to debug better, and hopefully find the issue... :+1:

**Comment by himelnagrana** [comment]
Thanks for such prompt reply.
We are using this within a modal (I forgot to mention previously). And we are using angular in twig within symfony framework.

So cannot really upload the whole piece of code as this will be large thing to share.
But still I am trying to share the related piece of code.
Any sort of help will be greatly appreciated.
Thanks.

````http://jsfiddle.net/aubks4ka/````

**Comment by himelnagrana** [comment]
It started working after assigning the css class provided in the example:

    section.droplet ul.files > li > img.droplet-preview {
        max-width: 5em;
        background-size: cover;
        background-repeat: no-repeat;
        height: 5em;
        width: 5em;
        background-color: white;
        box-shadow: 0 0 10px rgba(0, 0, 0, .25);
        border: 1px solid white;
        display: block;
    }

**Comment by Wildhoney** [comment]
Ah! Simple solution. I'm glad you fixed it! :-1:

**Comment by himelnagrana** [comment]
Thanks :+1:
