### ISSUE TITLE
Question: how to change the image preview size

### ISSUE THREAD

**Issue by mastermind1981** [Wildhoney/ngDroplet#23]
Hi,

I was wondering how to change in the css the size of the image preview?

Thank you in advance,

**Comment by Wildhoney** [comment]
For the example, it is [defined here](https://github.com/Wildhoney/ngDroplet/blob/master/example/css/Default.css#L171).

**Comment by mastermind1981** [comment]
Thank you ;)

**Comment by Wildhoney** [comment]
:kissing_smiling_eyes:
