### ISSUE TITLE
Doesn't work within AngularUI Bootstrap Accordions

### ISSUE THREAD

**Issue by Godwill** [Wildhoney/ngDroplet#27]
Its obviously something to do with the scope, the ng-droplet won't work with directives that create their own scope. Is there a way to fix this? Like not to attach the interface model to the $scope object directly. Instead of $scope.interface have something like $scope.something.interface? 

See here https://github.com/angular-ui/bootstrap/wiki/FAQ#my-input--select-element-doesnt-work-as-expected-inside-the-tab--accordion-directive

**Comment by Wildhoney** [comment]
I have no problem with it being `$scope.droplet.interface` if that's going to fix any issues you're having :+1: Please test it first by modifying the source code, and then open a PR if everything is good with it.

**Comment by Godwill** [comment]
Found a quicker workaround. Used dot notation on the model itself.

**Comment by Wildhoney** [comment]
Ah, good news! Glad you found a fix :+1:
