### ISSUE TITLE
 Not found progressbar.js

### ISSUE THREAD

**Issue by ThomGonzalez** [Wildhoney/ngDroplet#28]
Where I find the file progressbar.js

Regards.

**Comment by Wildhoney** [comment]
That's in [another repository](https://github.com/kimmobrunfeldt/progressbar.js/) &ndash; it's not needed for `ngDroplet`, only for the example. Try a `bower i` in the `ngDroplet` directory to install all of the depedencies.

Will move **progressbar.js** from `dependencies` to `devDependencies` :+1: Apologies.

**Comment by ThomGonzalez** [comment]
Thank very much.
