### ISSUE TITLE
User-defined callback for each file?

### ISSUE THREAD

**Issue by james-bell** [Wildhoney/ngDroplet#29]
I need to get two pieces of data from the user in addition to the image itself (a document type and a record locator).  Then I need to submit those in the POST, either in the URL or in the posted data.  setPostData and setRequestUrl seem to be used for *all* the files.  My next thought was to call one of those as each file was uploaded but I don't see an interface for that.  A user-defined callback that received a param of one "file" for each file being uploaded would be pretty handy.

**Comment by Wildhoney** [comment]
I can't envisage how we'd go about adding individual `POST` params for each file. What you could do, however, is add POST params that map the filenames to individual data, and then to resolve those on the server side.

For example you could have `POST` data:

```javascript
ngDroplet.setPostData({
    'myImage01.png': '...',
    'myImage02.png: '...'
});
```

...And then on the server side resolve that `POST` data to the uploaded images.

I suppose something like that could work :+1:
