### ISSUE TITLE
Not able to restrict size limit of the uploaded file

### ISSUE THREAD

**Issue by abinashbohidar** [Wildhoney/ngDroplet#31]
I am not able to restrict the size limit of the uploaded file considering I want to upload any file type. I tried doing something as below, but doesn't work. Quick response will be appreciated.

Snippet:-
 $scope.$on('$dropletFileAdded', function onFileAdd(event, args) {
        if (args.file.size>(3*1024 * 1024)) {
            //Exceeded Size which we must reject!
        	args.setType($scope.interface.FILE_TYPES.INVALID);
        }
 });

**Comment by Wildhoney** [comment]
Sorry &mdash; I suppose this is offending to respond 229 days late, but you're absolutely correct in your approach.

```javascript
$scope.$on('$dropletFileAdded', (_, model) => {
    model.file.size > 70000 && model.setType($scope.interface.FILE_TYPES.INVALID);
});
```

Using [new approach](https://github.com/Wildhoney/ngDroplet/issues/49) with attributes:

```javascript
$scope.onAdd = file => {
    file.file.size > 70000 && file.setType($scope.interface.FILE_TYPES.INVALID);
};
```
