### ISSUE TITLE
upload.html not present

### ISSUE THREAD

**Issue by vinovedeep** [Wildhoney/ngDroplet#32]
Hi I want to use this plugin but I am facing some difficulties, please help me
1)upload.html is not present
2)Error: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
3)Some files is missed in download and path are wrong

Thanks

**Comment by Wildhoney** [comment]
Did you `npm install && bower install`? Then `node example/server/default.js` and take a look at **localhost:5000**.

**Comment by vinovedeep** [comment]
I am very thankful for your quick response. I download the zip file and checking on my localhost.
May you please provide me upload.html here

**Comment by Wildhoney** [comment]
Sorry, `upload.html` being referenced is a little misleading, as it implies it's pointing to a physical file on the filesystem &ndash; instead [it's an API endpoint](https://github.com/Wildhoney/ngDroplet/blob/master/example/server/default.js#L14). You just need to run the Node server with `node example/server/default.js` and then access your `localhost` on port `5000` :+1:

**Comment by vinovedeep** [comment]
I am using this with the php not with the node js.
Below error is coming

POST http://localhost/ngDroplet-master/example/upload.html
	
404 Not Found
		0ms	
ng-droplet.js (line 613)
Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
parserFunction@http://localhost/ngDroplet-master/dist/ng-droplet.js:176:32
apply@http://localhost/ngDroplet-master/dist/ng-droplet.js:319:48
Pe/this.$get</l.prototype.$eval@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:125:301
Pe/this.$get</l.prototype.$apply@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:126:1
onError@http://localhost/ngDroplet-master/dist/ng-droplet.js:314:1
onReadyStateChange@http://localhost/ngDroplet-master/dist/ng-droplet.js:296:33
angular.min.js (line 102)
![screenshot](https://cloud.githubusercontent.com/assets/14088080/9679113/3b631c70-5309-11e5-8de3-e8f0a067ff40.png)

**Comment by Wildhoney** [comment]
You should be really using the Node server if you want the example to run correctly:

* Run `node example/server/default.js`
* Navigate to http://localhost:5000/

However, with your PHP if you return a valid JSON string, then it will be parsed correctly by `ngDroplet`.

**Comment by vinovedeep** [comment]
Ok Thanks, I will check.
