### ISSUE TITLE
Adding unsupported file type doesnt raise any error message

### ISSUE THREAD

**Issue by romain10009** [Wildhoney/ngDroplet#33]
So when I configure for example when I configure the ngDroplet to accept only Png files and I try to add some files of the wrong type, for instance Jpg, I get no errors. The files are not added, and there is only one unconvenient way to notify my user which is to listen for "$dropletFileAdded" event and do some checks on the file extension again.

Would it not be nice to have an event like "$dropletFileWrongType" raised so we don't need to repeat ourselves by checking for extensions again?

**Comment by Wildhoney** [comment]
Why not use:

```javascript
interface.getFiles(interface.FILE_TYPES.INVALID);
```

**Comment by Wildhoney** [comment]
Alternatively using the `$dropletFileAdded` approach, you could check if it's invalid:

```javascript
$scope.$on('$dropletFileAdded', (_, file) => {

    if (file.type & interface.FILE_TYPES.INVALID) {
        // Recently added file is invalid...
    }

});
```

**Comment by romain10009** [comment]
Sorry, I dind't re-read the docs. pardon me but to me "$dropletFileAdded" supposed that a file was added with success. Apparently not.

**Comment by Wildhoney** [comment]
Nope, not necessarily. You need to check its `type` &ndash; the utility methods such as `interface.getFiles(interface.FILE_TYPES.INVALID);` do this for you based on the bit value you pass in.

**Comment by romain10009** [comment]
Are you sure about the usage
    file.type & interface.File_TYPES.INVALID
because file.type gives me "image/jpg"  and FILE_TYPES contains ints... maybe I'm still doing something wrong.

**Comment by Wildhoney** [comment]
Yes, but you seem to be accessing the `type` property on the `File` object, rather than on the `DropletModel` object.

You need to use `DropletModel.type` as seen [in the `filterFiles` method](https://github.com/Wildhoney/ngDroplet/blob/master/components/ngDroplet.js#L490).

The `$dropletFileAdded` event passes through the `DropletModel` object, unless there's a bug somewhere...

**Comment by romain10009** [comment]
I really dont get it, this is the code I'm trying with now. I have : 
````javascript
$scope.$on('$dropletFileAdded',function(event,files){
    _.forEach(files,function(file){
        if (file.type & $scope.adminPhotoDroplet.FILE_TYPES.INVALID) {
          // Recently added file is invalid...
          $rootScope.addAlert('warning','Bad image type added',10000);
        }
    });
```
So on the scope I have $scope.adminPhotoDroplet. I inspected the "files" objects I get, I see nothing there, and also I dont see any "type" property on my $scope.adminPhotoDroplet model. could you tweak my code a bit to make it work?

**Comment by Wildhoney** [comment]
`$dropletFileAdded` is [emitted **once**](https://github.com/Wildhoney/ngDroplet/blob/master/components/ngDroplet.js#L395) for each file that has been *added* &mdash;  by iterating over `files` you're creating the confusion.

```javascript
$scope.$on('$dropletFileAdded', function(event, file) {
    
    if (file.type & $scope.adminPhotoDroplet.FILE_TYPES.INVALID) {
        // Recently added file is invalid...
        $rootScope.addAlert('warning','Bad image type added',10000);
    }
    
});
```

**Comment by romain10009** [comment]
Adam, would it be ok to talk that through, my skype is ryuuzaki57, i dont get any files back if i do $scope.adminPhotoDroplet.getFiles($scope.adminPhotoDroplet.FILE_TYPES.ALL) inside the event callback... is the code that sets the files not synchronous or hapening after raising the event?

**Comment by romain10009** [comment]
ok i found why this behaviour in the code : 
````javascript
 $scope.addFile = function addFile(file, type) {

                    // If the developer didn't specify the type then we'll assume it's a valid file
                    // that they're adding.
                    type = type || $scope.FILE_TYPES.VALID;

                    // Create the model and then register the file.
                    var model = new $scope.DropletModel();
                    model.load(file);
                    model.setType(type);

                    $scope.files.push(model);
                    return model;

                };
```
so the type is set after the load() function is called which is the one that broadcasts the fileAdded event. And also the files are not yet added to the $scope.files array, thats why when i try to get the files inside my listener for "$dropletFileAdded" is called, i get nothing. This looks like things are done in the wrong order. This is also why I had to add a 
```javascript
 $timeout($scope.uploadPictures, 100); //Grease.
```
inside the callback to make automatic file upload possible. I dont understand how all this has gone un-noticed.

**Comment by Wildhoney** [comment]
Because there are multiple ways of doing what you're after &mdash; I've pushed `v0.5.7` which *should* fix things :+1:

**Comment by romain10009** [comment]
ok, did a new commit, will my pull-request automaticcally update to latest commit?

**Comment by Wildhoney** [comment]
Yes, please see the PR to clean it up a little, and then I will merge and push.
