### ISSUE TITLE
404 Not Found causes SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by wernerglinka** [Wildhoney/ngDroplet#35]
First of all, thank you very much for a wonderful plugin..

I have installed the example from the download folder on a local server. I left the request url at upload.html so when I click the Upload Files button I get a 404 Not Found, just as expected. However, I also get 
<code>SyntaxError: Unexpected token < <br>
    at Object.parse (native) <br>
    at Object.parserFunction [as parserFn] (http://test/js/vendor/ng-droplet/ng-droplet.js:176:45) <br>
    at Object.apply (http://test/js/vendor/ng-droplet/ng-droplet.js:319:63) <br>
    at Scope.$get.Scope.$eval (http://test/js/vendor/angular/angular.js:15989:28) <br>
    at Scope.$get.Scope.$apply (http://test/js/vendor/angular/angular.js:16089:25) <br>
    at Object.onError (http://test/js/vendor/ng-droplet/ng-droplet.js:314:36) <br>
    at Object.onReadyStateChange (http://test/js/vendor/ng-droplet/ng-droplet.js:296:57)</code>

This causes the request to be aborted and $dropletError is never fired. Is this a known issue? Does anybody have an idea how to fix this. Any pointers would be welcome.

**Comment by Wildhoney** [comment]
Have you tried using the [`customParser` property on the options](https://github.com/Wildhoney/ngDroplet#custom-parser-function)? Ideally for a 404 you should **always** return a JSON format if your API is JSON-based. However, it's not always possible, and for that you simply need to `try catch` the `JSON.parse`.

Maybe something like the following would be better:

```javascript
interface.useParser(function myCustomerParserFn(responseText) {
    
    try {
        return JSON.parse(responseText);
    } catch (e) {
        // Something went wrong, so let's handle it...
    }
    
});
```

Currently there's no way to reject all of the files based on the 404, except handling that yourself by [iterating over the files](https://github.com/Wildhoney/ngDroplet#file-iteration) and [setting the type](https://github.com/Wildhoney/ngDroplet#file-model) to `FILE_TYPES.INVALID` (perhaps we should have a `FILE_TYPES.FAILED` for these instances).

Alternatively the module could pass a thunk to the `customParser` method, which you would invoke notifying Droplet of whether files succeeded or failed (or a `Promise`).

**Comment by wernerglinka** [comment]
Thank you for the quick reply Adam. I'll investigate

**Comment by wernerglinka** [comment]
Thanks again, your response helped me to device a solution.

**Comment by Wildhoney** [comment]
No problem :+1:
