### ISSUE TITLE
MEAN.JS integration not working.

### ISSUE THREAD

**Issue by GPnow** [Wildhoney/ngDroplet#39]
After bower install,i did the usual thing,changing config/all.js(including ngDroplet.js with its location),and public/config.js (adding [.....,"ngDroplet"] in the dependencies)respectively.
However when i used it in view it's not working,and also not even giving any error,so i am clueless.If anybody can suggest anything it'll be a nice starting point.

**Comment by Wildhoney** [comment]
Solved?

**Comment by GPnow** [comment]
Just needed to restart my computer,and it worked :)

**Comment by Wildhoney** [comment]
Haha... Classic :+1: Thank you, mate :)
