### ISSUE TITLE
Gray border around <img>

### ISSUE THREAD

**Issue by daedlock** [Wildhoney/ngDroplet#41]
When using `droplet-preview` the resulting images contains a gray border around them because that is what the browser would do if the `<img>` has no `[src]` attribute.

![photos 2016-01-03 18-48-17](https://cloud.githubusercontent.com/assets/842346/12079681/9bfd1e1e-b24a-11e5-9233-0fa81dd1f778.png)

**Comment by Wildhoney** [comment]
Please try again with https://github.com/Wildhoney/ngDroplet/commit/909304c1632916f23fe2a85ccb53f92bab9643ef :+1:

**Comment by daedlock** [comment]
@Wildhoney. Cool I did exactly that locally and wanted to submit a PR. But you were faster :)

**Comment by Wildhoney** [comment]
Haha! :+1: Thanks for raising the issue &ndash; I don't know how I didn't spot it.

**Comment by daedlock** [comment]
@Wildhoney I just started doing open source contributions recently. Would like to help you with any issues in the future as I am using ngDroplet in a production app. Also, there are some stuff missing in the documentation like how to customize the 'droplet' element on dragstart,end..etc. I had to read the code to get it
