### ISSUE TITLE
Using restify backend, req.files is always empty

### ISSUE THREAD

**Issue by ggoforth** [Wildhoney/ngDroplet#47]
This could totally be a misconfiguration on my end, but wanted to run it by the experts here :)  

I've got the following front end code:

```
    /**
     * When dropping is bootstrapped...
     */
    $scope.$on('$dropletReady', function whenDropletReady() {
      $scope.droplet.allowedExtensions(['png', 'jpg', 'bmp', 'gif']);
      $scope.droplet.setRequestHeaders({'Authorization': `Bearer ${User.currentUserToken}`});
      $scope.droplet.setRequestUrl(`${URLS.API}/github/upload`);
      $scope.droplet.useArray(false);
      $scope.droplet.defineHTTPSuccess([/2.{2}/]);

      /**
       * When a file is added, upload it right away.
       */
      $scope.$on('$dropletFileAdded', function whenDropletFileAdded(evt, file) {
        debugger;
        $scope.droplet.uploadFiles();
      });
```

This works great, and kicks off the upload.  When I love the `req.files` object in my restify endpoint, I get `{}`.  Do I need to set a name anywhere for the file being uploaded, or is that otherwise derived?  My backend code is just using `restify.bodyParser()` which should do the job of sticking the file in the req, but maybe I'm missing something.  

At any rate, I realize this is likely not an issue with ngDroplet but wanted to see if I'm missing a configuration somewhere that provides the name for the uploaded file that I could then find in `req.files` in restify.  Thanks!

**Comment by ggoforth** [comment]
<img width="787" alt="screenshot_2016-02-18_14_09_13" src="https://cloud.githubusercontent.com/assets/1167712/13159926/73be2cb8-d649-11e5-8ef7-3e3e9cce4175.png">

The request payload seems to be empty (notice at the bottom of the image).  That's expanded and scrolled to the bottom of the screen.

**Comment by Wildhoney** [comment]
It's the **Request Payload** you should be looking at &mdash; which is chopped off in your image. However by the looks of it there is *something* in there.

It should give you something like the following:

> ------WebKitFormBoundaryTIQjjVTcpUis7GJz
> Content-Disposition: form-data; name="file"; filename="dory.png"
> Content-Type: image/png
> ------WebKitFormBoundaryTIQjjVTcpUis7GJz--

I've noticed inconsistencies in the way files are handled on the server side &mdash; especially between Rails and Express, and that's why we have the [`useArray(false)` option](https://github.com/Wildhoney/ngDroplet/blob/master/components/ngDroplet.js#L588). You could try setting that to `true` and seeing if you have more luck that way.

Once you're receiving the files on the server side, they should be accessible via `file`. [In the example](https://github.com/Wildhoney/ngDroplet/blob/master/example/server/default.js) which uses Express, we use [`multer`](https://github.com/expressjs/multer) to parse the files, which puts them into the `request` object :+1:

**Comment by ggoforth** [comment]
<img width="1437" alt="screenshot 2016-02-18 14 29 59" src="https://cloud.githubusercontent.com/assets/1167712/13160419/2dd4dde8-d64c-11e5-8b14-5463db332811.png">

Here's another view, for some reason, this is all I get under the request payload.  I agree, there is something there, but it's truncated.  This is with current chrome on osx.

**Comment by ggoforth** [comment]
it also runs this upload like 700 times when I drop the file, but I'll work that out on my own :)

**Comment by Wildhoney** [comment]
Haha... Hmm.

Well I am on Chrome `48.0.2564.109` with OSX too. It seems strange that the **Request Payload** doesn't show the closing boundary as that's a must. Does the [example](http://ng-droplet.herokuapp.com/) show it any different to you?

![Screenshot](http://i.imgur.com/HXVByoA.jpg)

**Comment by ggoforth** [comment]
That example works and I see the closing boundary.  Damn, what am I doing wrong....don't want to waste your time on this, I'm sure I've misconfigured something, but all the events are firing as expected.  I'll test in another browser shortly and see if it changes anything.

**Comment by ggoforth** [comment]
Side note, changing it `useArray` to `true` didn't change anything.  My markup looks like:

```
        <div ng-model="droplet" data-droplet>
            <form name="replyBoxForm"
                  ng-submit="replyBox.send(replyBox.reply)"
                  ng-class="{open: replyBox.open}">
                <div class="form-group">
            <textarea name="reply"
                      required
                      class="form-control"
                      ng-model="replyBox.reply.body"
                      id="reply"></textarea>
                </div>

                <div class="pull-right button-bar">
                    <a ng-click="replyBox.open = !replyBox.open"
                       class="cancel-reply btn btn-link">Cancel
                    </a>
                    <button ng-disabled="replyBoxForm.$invalid"
                            class="btn btn-default send-reply">Send Reply
                    </button>
                </div>
            </form>
        </div>
```

**Comment by ggoforth** [comment]
<img width="604" alt="gittyup_io" src="https://cloud.githubusercontent.com/assets/1167712/13161396/3e291b5e-d652-11e5-9fad-f882aaceb2c2.png">

Same results in Firefox, though the console seems a bit different

**Comment by ggoforth** [comment]
Figured it out...apparently I needed to wrap my `uploadFiles` call with `isReady`.  This works:

'''
      /**
       * When a file is added, upload it right away.
       */
      $scope.$on('$dropletFileAdded', function whenDropletFileAdded() {
        if ($scope.dropletInterface.isReady()) {
          $scope.dropletInterface.uploadFiles();
        }
      });
'''

FYI, this directive is awesome, thanks for your work!

**Comment by Wildhoney** [comment]
Ah! Should have spotted that myself &mdash; glad you fixed it :+1:
