### ISSUE TITLE
$dropletFileAdded and $dropletSuccess called a lot

### ISSUE THREAD

**Issue by ggoforth** [Wildhoney/ngDroplet#48]
So I've got the uploads working, but I'm seeing my `$dropletFileAdded` and `$dropletSuccess` callbacks being called A LOT.  

![screenshot 2016-02-18 18 01 33](https://cloud.githubusercontent.com/assets/1167712/13164424/f0b9a862-d669-11e5-9bc6-999d0684b172.png)

Is this normal?  I'm seeing multiple calls to my backend and multiple attempts to upload to s3. Only one file is uploaded to s3 (but I'm assuming it's overwriting the same file over and over).  

I'm using this inside one of my own custom directives, so there are multiples of these on  page, but it doesn't seem to correspond with how many times I'm seeing these events be fired.

**Comment by ggoforth** [comment]
![screenshot 2016-02-18 18 01 33](https://cloud.githubusercontent.com/assets/1167712/13164477/6c53b6ca-d66a-11e5-8153-0b4041fbbccd.png)

**Comment by ggoforth** [comment]
Sorry, dunno how that got closed :)

**Comment by ggoforth** [comment]
To add a little more info, the app I'm building is a feed of events from thrid party apis.  There is a reply box on each item (pictured below in the pink squares).  The reply box directive contains the droplet directive, so there could be N number of droplets on a page.  Possible that multiple droplets could be causing the issue of calling all these events so many times?

<img width="904" alt="dropplet" src="https://cloud.githubusercontent.com/assets/1167712/13167925/b3c61ff8-d68c-11e5-838a-7d809e6e643e.png">

**Comment by ggoforth** [comment]
Think I figured this out.  I was binding to the file added and success events inside the $dropletReady event.  I'm guessing this gets called often, and it was rebinding to those same events multiple times.  Moving those bindings out of the $dropletReady fixed the issue.

**Comment by Wildhoney** [comment]
Yep &mdash; that makes sense. Those events will propagate throughout the system, so ideally handle them in a single location.
