### ISSUE TITLE
Different property name

### ISSUE THREAD

**Issue by iwannabaa** [Wildhoney/ngDroplet#59]
Is there a way to use a different property name other than `file` or `file[]`. This is required by the api I need to send the image to.

**Comment by Wildhoney** [comment]
Nope. But if you want to open a PR for that I'm happy to merge it in.

**Comment by iwannabaa** [comment]
I added support for this #60 What do you think?

**Comment by Wildhoney** [comment]
Looks great &mdash; all merged in and released.
