### ISSUE TITLE
NPM Published version has too strict engine specified still

### ISSUE THREAD

**Issue by RobHarrisAZ** [Wildhoney/ngDroplet#72]
This looks like is has been fixed in the repo but not published to npm so I have to override the engine checks in yarn to install.  NPM version of 0.7.0 has this:  engines: { node: '>=4.1.1 <7.0.0' }. Repo has "engines": {
    "node": ">=7.0.0"
  }

**Comment by Wildhoney** [comment]
Sorry. Published `v0.7.1` 👍
